#docker-compose.yml
version: '3.4'
services:

  navicell-db:
    image: mongo:4.2.9
    container_name: navicell-db
    restart: always
    volumes:
      - db:/data/db
      - config-db:/data/configdb
      
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: navicell

  navicell:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: vnoel/navicell:3.0.0b10
    container_name: navicell
    ports:
      - "127.0.0.1:8088:80"
    user: root
    volumes:
      - maps:/var/navicell/site/docroot/navicell/maps
      - data:/var/navicell/site/docroot/navicell/data    
    depends_on:
      - navicell-db
    restart: unless-stopped

      
volumes:
  db:
  config-db:
  maps:
  data:
